export * from './account'
export * from './home'
export * from './detail'
export * from './search'
export * from './login'
export * from './getstarted'
export * from './register'
export * from './indoormap'