export * from './home';
export * from './detail';
export * from './search';
export * from './login';
export * from './splash';
export * from './register';
export * from './indoormap';
export * from './listplace';
export * from './account';
